version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - seven_network
    #env_file:
    #  - .env
    environment:
        DEEPGRAM_API_KEY: 2855fcd8ca79dce205acf7139a218c958c31abea
    #   DB_HOST: ${DB_HOST?Variable not set}
    #   DB_USER: ${DB_USER?Variable not set}
    #   DB_PASSWORD: ${DB_PASSWORD?Variable not set}
    #   DB_DATABASE: ${DB_DATABASE?Variable not set}
    container_name: seven_backend

networks:
  seven_network:
